# Description : delete all items (container, network) from previous docker-compose (to avoid error with existing items)
# file : _purge_old_compose_items.yml

- name: Get docker container list
  command: docker ps -aq
  register: docker_container_list

- name: Remove all Docker containers
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ docker_container_list.stdout_lines }}"

- name: Prune Docker networks
  command: docker network prune -f